### ISSUE TITLE
UnimplementedError with a column that has an interval type

### ISSUE THREAD

**Issue by Rapougnac** [isoos/postgresql-dart#219]
Hi, when I try to select a table that has a column type with a default value, I'm always getting this error:
```
Unhandled exception:
UnimplementedError
#0      PostgresBinaryDecoder.convert (package:postgres/src/binary_codec.dart:498:40)
#1      Query.addRow.<anonymous closure> (package:postgres/src/query.dart:173:41)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
....
```

Here's a small reproductible example:
```dart
import 'package:postgres/postgres.dart';

void main(List<String> args) async {
  final connection = PostgreSQLConnection('localhost', 5432, 'db', username: 'username', password: 'pwd');
  await connection.open();

  await connection.query(
    '''
      CREATE TABLE IF NOT EXISTS users
      (id SERIAL PRIMARY KEY, name TEXT NOT NULL, max_age INTERVAL DEFAULT ('1 day'::interval) NOT NULL)
    ''',
  );

  await connection.query("INSERT INTO users (name) VALUES ('Alice')");

  final result = await connection.mappedResultsQuery('SELECT * FROM users');

  for (final row in result) {
    print(row);
  }
}
```
Not sure why it's happening though...

**Comment by isoos** [comment]
Hm, looks like the current implementation is limited to 8-bytes long microseconds, and doesn't handle days (or larger) components of the 16-bytes Postgres `interval`. I think the correct thing to do is to stop using `Duration` for this, and introduce an `Interval` data type.
